version: "3.8"

services: 
  backend-cors:
    image: node:13.12.0-alpine
    container_name: api-cors
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - 8081:8080
    volumes: 
      - .:/app
